### ISSUE TITLE
No Signal/Quality or Sgn/Snr info

### ISSUE THREAD

**Issue by zampedro** [vl-nix/dvbv5-gtk#1]
I'm using a RTL2832U+E4000 usb stick, Signal C/N and postBER level work only with dvbv5-scan.
There is no other linux software that works, maybe tvheadend.
After a quick look at the code i see scan_set_level void in scan.c and the output of dvbv5-scan:

$ dvbv5-scan -F dddit
Scanning frequency #1 530000000
Viterbi(0x07) Signal= 0,00% C/N= 16,24dB
Scanning frequency #2 594000000
Lock   (0x1f) Signal= 93,33% C/N= 27,46dB postBER= 235x10^-6
....

so i change scan_set_level into:

static void scan_set_level ( Scan *scan, char *data, bool look )
{
	if ( g_strrstr(data,"Viterbi")!=NULL ) {
	    char **lines = g_strsplit ( data, " ", 0 );
	    level_set_sgn_snr ( scan->level, atof ( lines[2] ), atof ( lines[4] ), look );
	    g_strfreev ( lines );
	}
	else {
	    char **lines = g_strsplit ( data, " ", 0 );
	    level_set_sgn_snr ( scan->level, atof ( lines[5] ), atof ( lines[7] ), look );
	    g_strfreev ( lines );
	}
}

not so clean code but it works.
Regards

**Comment by vl-nix** [comment]
Thank you very much!

Fixed.

Regards,
Stepan

**Comment by vl-nix** [comment]
Q: how important is the postBER parameter?

DTV_BER ( postBER ): Bit Error Rate

**Comment by mchehab** [comment]
> Q: how important is the postBER parameter?
> 
> DTV_BER ( postBER ): Bit Error Rate

Well, preBER, postBER, CNR and block error count are all things used to monitor the signal quality. They're usually correlated.

postBER measures non-corrected errors.

**Comment by vl-nix** [comment]
Thank

**Comment by zampedro** [comment]
The fix doesn't work for me.
I get Signal/Snr info only in lines[5] and lines[7] when then tuner is Lock, so:


static void scan_set_level ( Scan *scan, char *data, bool look )
{
	/* FIXME: zampedro ( issue: No Signal/Quality or Sgn/Snr info #1 ) */
	/* FIXME: checking empty data */
	if ( data )
	{
		if ( g_strrstr ( data, "=" ) )
		{
			char **lines = g_strsplit ( data, " ", 0 );
			if ( g_strrstr(data,"Viterbi")!=NULL ) {
				level_set_sgn_snr ( scan->level, atof ( lines[2] ), atof ( lines[4] ), look );
			} else {
				level_set_sgn_snr ( scan->level, atof ( lines[5] ), atof ( lines[7] ), look );
			}
			g_strfreev ( lines );
		}
		else
		{
			level_set_sgn_snr ( scan->level, 0, 0, look );
		}
	}
	else
	{
		level_set_sgn_snr ( scan->level, 0, 0, look );
	}
}

Regards

**Comment by vl-nix** [comment]
Okay, I see. If this is a special case, you can create a separate rule for the RTL2832U device.

**Comment by vl-nix** [comment]
The problem is not with postBER, but with Internationalization.
Now it will work.

Regards,
Stepan

**Comment by zampedro** [comment]
Now Signal/Snr indication works, but most of the scans fail:
Scanning frequency #2 594000000
ERROR    dvb_read_sections: no data read on section filter
ERROR    error while waiting for PAT table

Command line dvbv5-scan still works good.

Not related to this issue,i suggest to change the line
LIBDVBV5 = $(shell find /usr/lib -type f -name $(library).so*)
to something like 
LIBDVBV5 = `pkg-config libdvbv5 --libs`
in the file Makefile, for those who have libdvbv5 in /usr/lib64.

Best regards.

**Comment by vl-nix** [comment]
> but most of the scans fail

Can try:
Set: File freqs-only - true ( analogue -F )

**Comment by zampedro** [comment]
I have a conf test file dddit with 2 channels, dvbv5-scan always works and dvbv5-scan-gtk sometimes works.
[dddit.txt](https://github.com/vl-nix/dvbv5-scan-gtk/files/4363355/dddit.txt)
[output_dvbv5-scan.-gtk.txt](https://github.com/vl-nix/dvbv5-scan-gtk/files/4363359/output_dvbv5-scan.-gtk.txt)
[output_dvbv5-scan.txt](https://github.com/vl-nix/dvbv5-scan-gtk/files/4363362/output_dvbv5-scan.txt)

Maybe it is another issue not related with this.

**Comment by vl-nix** [comment]
Thank

**Comment by vl-nix** [comment]
You can try the following: build a program with a library

Open the Makefile and comment on the library search:
# LIBDVBV5 = $(shell find /usr/lib -type f -name $(library).so*)

make

Size
ls -sh

**Comment by vl-nix** [comment]
> Maybe it is another issue not related with this.

Ok

**Comment by vl-nix** [comment]
> Not related to this issue,i suggest to change the line
LIBDVBV5 = $(shell find /usr/lib -type f -name $(library).so*)
to something like
LIBDVBV5 = pkg-config libdvbv5 --libs
in the file Makefile, for those who have libdvbv5 in /usr/lib64.

Open new issue.

**Comment by vl-nix** [comment]
> I have a conf test file dddit with 2 channels, dvbv5-scan always works and dvbv5-scan-gtk sometimes works.
dddit.txt
output_dvbv5-scan.-gtk.txt
output_dvbv5-scan.txt

Maybe it is another issue not related with this.

Open new issue.

**Comment by zampedro** [comment]
New version is ok, works with embedded libdvbv5 and system libdvbv5.
I discovered that previous version has problems (failed scans) when the stick is connected to a usb hub.
I think there is no need to open a new issue.
Regards
