### ISSUE TITLE
Звуковая индикация уровня/качества сигнала

### ISSUE THREAD

**Issue by Ro-Den** [vl-nix/dvbv5-gtk#6]
Здравствуйте!

Можете "добавить" в программу звуковую индикацию уровня/качества сигнала?

Нужно для настройки антенны. Ни в одной программе под Линукс не нашёл. Есть только подача сигнала в случае захвата частоты.

В Windows данная функция обычно реализуется проигрыванием соответствующего файла wav. Думаю, в Линукс можно также использовать какой-нибудь синтезатор речи TTS.

**Comment by vl-nix** [comment]
Для начала добавлено ( beep ), два звуковых сигнала ( один за другим )

1. Beep: 
Signal 0-25: beep 500 Hz
Signal 25-50: beep 1000 Hz
Signal 50-75: beep 2000 Hz
Signal 75-100: beep 3000 Hz

2. Beep:
Quality 0-25: beep 500 Hz
Quality 25-50: beep 1000 Hz
Quality 50-75: beep 2000 Hz
Quality 75-100: beep 3000 Hz

**Comment by vl-nix** [comment]
Если необходимо заменить beep - звуковой сигнал, на синтезатор речи,
в файле dvbv5.c нужно заменить все содержимое функции - dvbv5_dvb_fe_beep,
на следующий код ( в релиз этот код не войдет ):

	if ( gtk_toggle_button_get_active ( GTK_TOGGLE_BUTTON ( dvbv5->toggle_fe_beep ) ) )
	{
		time_t t_cur;
		time ( &t_cur );

		if ( ( t_cur - dvbv5->t_fe_start ) >= 4 )
		{
			time ( &dvbv5->t_fe_start );

			uint get_sgl = (sgl * 100) / 0xffff;
			uint get_snr = (snr * 100) / 0xffff;

			char *text = g_strdup_printf ( "espeak -ven \"%d  %d\"", get_sgl, get_snr );
			system ( text );
			free ( text );
		}
	}

**Comment by vl-nix** [comment]
Add: Beeps

Beep 1:
Signal 0-25: beep 500 Hz
Signal 25-50: beep 1000 Hz
Signal 50-75: beep 2000 Hz
Signal 75-100: beep 3000 Hz

Beep 2:
Quality 0-25: beep 500 Hz
Quality 25-50: beep 1000 Hz
Quality 50-75: beep 2000 Hz
Quality 75-100: beep 3000 Hz

beep 1 ( 250 ms )  --  timeout ( 250 ms )  --  beep 2 ( 250 ms )  --  timeout  ( 2250 ms )

**Comment by Ro-Den** [comment]
Спасибо!

Бибикает и говорит тоже. Не думал, что это можно так быстро реализовать.

А вот сами dvb-tools, а имеено `dvb-fe-tool -A`, бибикать отказываются:

> -A, --acoustical
                             beeps if signal quality is good. Also enables
                             femon mode. Please notice that console beep should
                             be enabled on your wm.

Не знаешь в чём может быть дело? Что значит "signal quality is good" ? "console beep" я вроде бы включил, но только не в wm (Window Manager, насколько я понимаю), а в самой KDE Konsole...

И ещё, откуда в программе берутся значения Signal (Sgn) / Quality (Snr) ? Вот что мне выдаёт команда `dvbv5-zap` на 2-х транспондерах с максимальным и минимальным сигналом, соответственно:

>Lock   (0x1f) Signal= -34,80dBm C/N= 10,60dB UCB= 0
          Layer A: Signal= 168887563046057,91% C/N= 53,05%

>Lock   (0x1f) Signal= -38,85dBm C/N= 9,40dB UCB= 0
          Layer A: Signal= 168887563046053,91% C/N= 47,05%

В Dvbv5-Gtk значения примерно следующие:

>Signal (Sgn) / Quality (Snr): 46% / 16%

>Signal (Sgn) / Quality (Snr): 40% / 14%

Кстати, можно как-то вывести эту информацию в терминал? Я пробовал `dvbv5-gtk -v` и `dvbv5-gtk -d` - безуспешно.

Да, и у меня dvb-tools (v4l-utils) версии 1.18.0-2build1. Может проблема в этом?

**Comment by vl-nix** [comment]
> А вот сами dvb-tools, а имеено `dvb-fe-tool -A`, бибикать отказываются:

В файле - utils/dvb/dvb-fe-tool.c - можно к примеру заменить строку:
- fprintf(fd, "\a");
на код  ( частота звука Hz: -f 1000; длина звука 250 мс: sleep .25 ):
- system ( "speaker-test -t sine -f 1000 -l 1 & sleep .25 && kill -9 $!" );

Для управления звуком, нужно усложнять код программы ...


> Кстати, можно как-то вывести эту информацию в терминал? Я пробовал dvbv5-gtk -v и dvbv5-gtk -d - безуспешно.

А зачем? Все же программа с графическим интерфейсом ...
dvbv5-gtk берет данные от программы dvb-fe-tool

Если очень необходимо, то можно добавить одну строку кода в файл
dvbv5.c функция - dvbv5_dvb_fe_beep
- printf ( "Signal %d ( %d ) | Quality %d ( %d ) \n", (sgl * 100) / 0xffff, sgl, (snr * 100) / 0xffff, snr );


> Да, и у меня dvb-tools (v4l-utils) версии 1.18.0-2build1. Может проблема в этом?

Нет

**Comment by Ro-Den** [comment]
>А зачем?

Для отладки, например. Мне, как программисту-любителю, нравится всю информацию печатать. Сразу видно, где накосячил.

С уровнем/качеством сигнала я вроде почти разобрался. Данные, приведённые выше, получены на нестандартном ядре v4l-updatelee с модифицированным драйвером. На базовом со стандартным драйвером никаких расхождений в показаниях нет, но данные "немного" другие:

>Lock   (0x1f) Signal= 66,00% C/N= 24,20% postBER= 0

>Lock   (0x1f) Signal= 61,00% C/N= 19,20% postBER= 0

С другой стороны, в стандартном драйвере не реализована автоподстройка частоты, а на моём старом конвертере (LNB) нижние частоты "уплыли" почти на 4MHz. И в dvb-tools никаких custom LNB, насколько я понимаю, разработчики не предусмотрели, а параметры стандартных конвертеров вместо файла настроек зачем-то запихали в код программы - так просто не поменяешь. В нормальных программах проблема с частотами решается элементарным указанием LOF1=9754. Здесь же придётся править "таблицы" транспондеров (initial files).

Надо будет ещё с Windows показания сравнить. Там должны быть "правильные".

**Comment by vl-nix** [comment]
> LOF1=9754

В [Helia-light](https://github.com/vl-nix/helia-light) - можно указать вручную: 
( LNB LOf1 MHz; LNB LOf2 MHz; LNB Switch MHz )
Scaner -> Dvb-S/S2 -> Lnb -> Manual -> ** 🤚 ** 

Photo - https://yadi.sk/i/E8jRc0JkAwF2Jw

**Comment by Ro-Den** [comment]
А в Helia-light откуда берутся значения Signal (Sgn) / Quality (Snr) ?

На стандартном ядре от Линуса всё "нормально", а на нестандартном v4l-updatelee показания существенно разнятся. Вот, что примерно выдаёт Helia-light:

>Signal (Sgn) / Quality (Snr): 74% / 52%

>Signal (Sgn) / Quality (Snr): 66% / 64%

В Dvbv5-Gtk значения примерно те же, что и позавчера:

>Signal (Sgn) / Quality (Snr): 47% / 16%

>Signal (Sgn) / Quality (Snr): 41% / 14%

**Comment by vl-nix** [comment]
> А в Helia-light откуда берутся значения Signal (Sgn) / Quality (Snr) ?

[Gstreamer 1.0](https://gstreamer.freedesktop.org) ⇨ [GstDvbSrc](https://gstreamer.freedesktop.org/documentation/dvb/dvbsrc.html#dvbsrc)

**Comment by vl-nix** [comment]
Шаг первый:
простая программа для получения данных от DVB  устройства
Установить устройство:  const char *fd_name = "/dev/dvb/adapter0/frontend0";

#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/dvb/frontend.h>

// gcc dvb-info.c -o dvb-info
// ./dvb-info

static void dvb_name ( int fd )
{
	struct dvb_frontend_info info;

	if ( ( ioctl ( fd, FE_GET_INFO, &info ) ) == -1 ) return;

	printf ( "Dvb Device: %s \n", info.name );
}

static uint dvb_get_lock ( int fd )
{
	enum fe_status status;

	if ( ( ioctl ( fd, FE_READ_STATUS, &status ) ) == -1 ) return 0;

	if ( status & FE_HAS_LOCK ) return 1;

	return 0;
}

static uint dvb_get_sgl_snr ( int fd, uint num )
{
	uint data = 0;

	if ( ioctl ( fd, num, &data ) == -1 ) data = 0;

	return data;
}

static int dvb_open_device ( const char *fd_name )
{
	int fd = open ( fd_name, O_RDONLY, 0 );

	return fd;
}

static void dvb_close_device ( int fd )
{
	close ( fd );
}

int main ()
{
	const char *fd_name = "/dev/dvb/adapter0/frontend0";

	int i = 0, count = 1000;
	int fd = dvb_open_device ( fd_name );

	if ( fd == -1 ) return 1;

	dvb_name ( fd );

	for ( i = 0; count; i++ )
	{
		sleep (1);

		uint lck = dvb_get_lock ( fd );
		uint sgl = dvb_get_sgl_snr ( fd, FE_READ_SIGNAL_STRENGTH );
		uint snr = dvb_get_sgl_snr ( fd, FE_READ_SNR );

		printf ( "Signal %d ( Lock %s ) Quality %d \n",  sgl, ( lck ) ? "Ok" : "No", snr );
	}

	dvb_close_device ( fd );

	return 0;
}

**Comment by vl-nix** [comment]
В программу внесены изменения:
сейчас данные статистики берутся не от dvb-fe-tool, а напрямую от Dvb устройства

**Comment by Ro-Den** [comment]
Что-то моему STV090x Multistandard (Omicom S2 PCI Rev.3) последние изменения не понравились. На обоих ядрах программа виснет после:

>** Message: 04:19:10.947: _dvbv5_dvb_zap_init:: Zap Ok.
** Message: 04:19:11.550:   PAT: DMX_SET_PES_FILTER 0 (0x0000)
** Message: 04:19:11.560:   PMT: DMX_SET_PES_FILTER 750 (0x02ee)
** Message: 04:19:11.560:   VIDEO: DMX_SET_PES_FILTER 751 (0x02ef)
** Message: 04:19:11.560:   AUDIO: DMX_SET_PES_FILTER 752 (0x02f0)

Кстати, зачем было использовать `dvb-fe-tool` ? Вроде `dvbv5-zap` выдаёт те же самые значения:

>Lock   (0x1f) Signal= 66,00% C/N= 24,80% postBER= 0

И наверное лучше C/N отображать с точностью до десятых. А ещё лучше: `Quality=f(BER)`. Понятно, что при BER=0, Quality=100%.

И ещё. Можно сделать, чтобы программа запоминала последнюю выбранную папку?

**Comment by vl-nix** [comment]
Обновлено

**Comment by vl-nix** [comment]
> На обоих ядрах программа виснет

Странно

> зачем было использовать dvb-fe-tool ? Вроде dvbv5-zap выдаёт те же самые значения

dvbv5-zap - для вывода статистики использует функции dvb-fe-tool

**Comment by vl-nix** [comment]
> Можно сделать, чтобы программа запоминала последнюю выбранную папку?

Можно перенести файл мышкой

Drag and Drop: 
* Initial file ---> Scan-Box
* dvb_channel.conf ---> Zap-Box

**Comment by Ro-Den** [comment]
Обновление сработало!

>dvbv5-zap - для вывода статистики использует функции dvb-fe-tool

Тогда почему на нестандартном ядре значения выдаваемые dvbv5-zap и dvb-fe-tool совпадают:

>Lock (0x1f) Signal= -34,80dBm C/N= 10,60dB UCB= 0
Layer A: Signal= 168887563046057,91% C/N= 53,05%

Такие же цифры (Signal= -34,80dBm C/N= 10,60dB) показывает Tvheadend, VDR (plugin Femon) и программы updateDVB и tune-s2, "заточенные" под нестандартное ядро.

В то время как в Dvbv5-Gtk цифры совсем другие:

>Signal (Sgn) / Quality (Snr): 46% / 15%

И, наконец, третий вариант от Helia-light (GstDvbSrc):

>Signal (Sgn) / Quality (Snr): 73% / 51%

Подозреваю, что Tvheadend и VDR (plugin Femon) умеют работать с модифицированным драйвером, а Dvbv5-Gtk и Helia-light (GstDvbSrc) - не умеют. Но всё равно же цифры не с потолка берутся...

**Comment by vl-nix** [comment]
Patch ( decibel ):

diff --git a/gtk/src/dvbv5.c b/gtk/src/dvbv5.c
index e8b6b83..07908e3 100644
--- a/gtk/src/dvbv5.c
+++ b/gtk/src/dvbv5.c
@@ -811,11 +811,11 @@ static void dvbv5_set_status_server ( Dvbv5 *dvbv5 )
 	gtk_label_set_markup ( dvbv5->label_rec, text );
 }
 
-static void dvbv5_set_level ( uint16_t sgl, uint16_t snr, bool fe_lock, Dvbv5 *dvbv5 )
+static void dvbv5_set_level ( uint16_t sgl, uint16_t snr, bool fe_lock, bool decibel, Dvbv5 *dvbv5 )
 {
 	/* FIXME: zampedro ( issue: No Signal/Quality or Sgn/Snr info #1 ) */
 
-	level_set_sgn_snr ( dvbv5->level, (sgl * 100) / 0xffff, (snr * 100) / 0xffff, fe_lock );
+	level_set_sgn_snr ( dvbv5->level, sgl, snr, fe_lock, decibel );
 
 	if ( dvbv5->zap->stm_status )
 	{
@@ -876,19 +876,16 @@ static bool dvbv5_dvb_fe_get_stats ( Dvbv5 *dvbv5 )
 	}
 
 	fe_status_t status;
-	dvb_fe_retrieve_stats ( parms, DTV_STATUS, &status );
-
-	uint32_t freq = 0, sgl = 0, cnr = 0;
-	bool sat = FALSE, fe_lock = FALSE;
-	if ( status & FE_HAS_LOCK ) fe_lock = TRUE;
+	uint32_t freq = 0, sgl = 0, snr = 0, qual = 0;
+	bool sat = FALSE, fe_lock = FALSE, decibel = FALSE;
 
-	// if ( ioctl ( parms->fd, FE_READ_SNR, &snr ) == -1 ) cnr = 0;
-	// if ( ioctl ( parms->fd, FE_READ_SIGNAL_STRENGTH, &sgl ) == -1 ) sgl = 0;
-
-	dvb_fe_retrieve_parm  ( parms, DTV_FREQUENCY, &freq );
-	dvb_fe_retrieve_stats ( parms, DTV_STAT_CNR,  &cnr  );
+	dvb_fe_retrieve_parm  ( parms, DTV_FREQUENCY, &freq   );
+	dvb_fe_retrieve_stats ( parms, DTV_STATUS,    &status );
+	dvb_fe_retrieve_stats ( parms, DTV_QUALITY,   &qual   );
+	dvb_fe_retrieve_stats ( parms, DTV_STAT_CNR,  &snr    );
 	dvb_fe_retrieve_stats ( parms, DTV_STAT_SIGNAL_STRENGTH, &sgl );
 
+	if ( status & FE_HAS_LOCK ) fe_lock = TRUE;
 	if ( dvb_fe_is_satellite ( parms->current_sys ) ) sat = TRUE;
 
 	if ( dvbv5->freq_scan > 0 )
@@ -896,14 +893,23 @@ static bool dvbv5_dvb_fe_get_stats ( Dvbv5 *dvbv5 )
 	else
 		dvbv5_stats_update_freq ( dvbv5->label_freq, ( sat ) ? freq / 1000 : freq / 1000000, 0, "L-Freq:  ", "MHz" );
 
+	struct dtv_stats *stat = dvb_fe_retrieve_stats_layer ( parms, DTV_STAT_SIGNAL_STRENGTH, 0 );
+
+	if ( stat )
+	{
+		if ( stat->scale == FE_SCALE_DECIBEL ) decibel = TRUE;
+	}
+
+	printf ( "Quality %d | Signal %d ( %d ) | Snr / Cnr %d ( %d ) | decibel %s \n", qual, (sgl * 100) / 0xffff, sgl, (snr * 100) / 0xffff, snr, ( decibel ) ? "True" : "False" );
+
 	if ( sgl > 0 )
 	{
-		dvbv5_set_level ( sgl, cnr, fe_lock, dvbv5 );
-		dvbv5_dvb_fe_beep ( sgl, cnr, dvbv5 );
+		dvbv5_set_level ( sgl, snr, fe_lock, decibel, dvbv5 );
+		( !decibel ) dvbv5_dvb_fe_beep ( sgl, snr, dvbv5 );
 	}
 	else
 	{
-		level_set_sgn_snr  ( dvbv5->level, 0, 0, FALSE   );
+		level_set_sgn_snr  ( dvbv5->level, 0, 0, FALSE, FALSE );
 		gtk_label_set_text ( dvbv5->label_freq, "Freq: " );
 		gtk_label_set_text ( dvbv5->label_rec, "" );
 	}
@@ -936,7 +942,7 @@ static bool dvbv5_dvb_fe_show_stats ( Dvbv5 *dvbv5 )
 
 		if ( dvbv5->window )
 		{
-			level_set_sgn_snr  ( dvbv5->level, 0, 0, FALSE   );
+			level_set_sgn_snr  ( dvbv5->level, 0, 0, FALSE, FALSE );
 			gtk_label_set_text ( dvbv5->label_freq, "Freq: " );
 			gtk_label_set_text ( dvbv5->label_rec, "" );
 
diff --git a/gtk/src/level.c b/gtk/src/level.c
index f562c86..d159fd2 100644
--- a/gtk/src/level.c
+++ b/gtk/src/level.c
@@ -9,13 +9,13 @@
 
 #include "level.h"
 
-void level_set_sgn_snr ( Level *level, double sgl, double snr, bool fe_lock )
+void level_set_sgn_snr ( Level *level, double sgl, double snr, bool fe_lock, bool decibel )
 {
-	gtk_progress_bar_set_fraction ( level->bar_sgn, sgl/100 );
-	gtk_progress_bar_set_fraction ( level->bar_snr, snr/100 );
+	gtk_progress_bar_set_fraction ( level->bar_sgn, ( decibel ) ? 0 : sgl / 0xffff );
+	gtk_progress_bar_set_fraction ( level->bar_snr, ( decibel ) ? 0 : snr / 0xffff );
 
-	char *texta = g_strdup_printf ( "Sgn %d%s", (int)sgl, "%" );
-	char *textb = g_strdup_printf ( "Snr %d%s", (int)snr, "%" );
+	char *texta = ( decibel ) ? g_strdup_printf ( "Signal %.2fdBm", sgl / 1000 ) : g_strdup_printf ( "Signal %d%s",  (uint)(sgl * 100) / 0xffff, "%" );
+	char *textb = ( decibel ) ? g_strdup_printf ( "Quality %.2fdB", snr / 1000 ) : g_strdup_printf ( "Quality %d%s", (uint)(snr * 100) / 0xffff, "%" );
 
 	const char *format = NULL;
 
diff --git a/gtk/src/level.h b/gtk/src/level.h
index 4ae1315..499b9f0 100644
--- a/gtk/src/level.h
+++ b/gtk/src/level.h
@@ -27,6 +27,6 @@ struct _Level
 
 Level * level_new (void);
 void level_destroy ( Level *level );
-void level_set_sgn_snr ( Level *level, double sgl, double snr, bool fe_lock );
+void level_set_sgn_snr ( Level *level, double sgl, double snr, bool fe_lock, bool decibel );
 
 #endif

**Comment by Ro-Den** [comment]
>patch-decibel.diff.tar.gz

Не собирается:

>FAILED: dvbv5-gtk@exe/gtk_src_dvbv5.c.o

>../gtk/src/dvbv5.c: In function ‘dvbv5_dvb_fe_get_stats’:
../gtk/src/dvbv5.c:908:5: warning: statement with no effect [-Wunused-value]
  908 |   ( !decibel ) dvbv5_dvb_fe_beep ( sgl, snr, dvbv5 );

Ругается на отсутствие `;` перед `‘dvbv5_dvb_fe_beep’`:

>../gtk/src/dvbv5.c:908:15: error: expected ‘;’ before ‘dvbv5_dvb_fe_beep’
  908 |   ( !decibel ) dvbv5_dvb_fe_beep ( sgl, snr, dvbv5 );

>At top level:
../gtk/src/dvbv5.c:846:13: warning: ‘dvbv5_dvb_fe_beep’ defined but not used [-Wunused-function]
  846 | static void dvbv5_dvb_fe_beep ( uint16_t sgl, uint16_t snr, Dvbv5 *dvbv5 )

>[11/13] Compiling C object 'dvbv5-gtk@exe/gtk_src_zap-signals.c.o'.
ninja: build stopped: subcommand failed.

Я добавил после скобки: `( !decibel );`.

Теперь только выдаёт предупреждение `statement with no effect`:

>../gtk/src/dvbv5.c:908:5: warning: statement with no effect [-Wunused-value]
  908 |   ( !decibel ); dvbv5_dvb_fe_beep ( sgl, snr, dvbv5 );

Децибелы показывает:

>Signal 30.67dBm / Quality 11.10dB

Значение Signal почему-то положительное. В `dvbv5-zap` оно отрицательное:

>Lock   (0x1f) Signal= -34,67dBm C/N= 11,10dB UCB= 0
          Layer A: Signal= 168887563046057,91% C/N= 55,56%

Уровень сигнала в "процентах" похоже вычисляется по формуле `Level=100+RFLevel` с округлением: `65%=100+(-34,67dBm)`.

А C/N в "процентах" равен C/N в dB, умноженному на 5: `55,56%≈5*11,10dB`.

**Comment by vl-nix** [comment]
Спасибо!

FIX: DECIBEL / RELATIVE ( Ro-Den issue: #6 )

**Comment by Ro-Den** [comment]
С этими децибелами похоже не всё так просто!

Данные для расчетов выдают драйвера ТВ-тюнеров. И что в них может быть заложено заранее не известно. Например, мой STV090x Multistandard в качестве уровня сигнала на стандартном ядре выдаёт `100+RFLevel`, а на модифицированном - `RFLevel`. В принципе ничего сложного:
1. Нужно определить какое у нас значение: положительное или отрицательное,
2. Если значение положительное, то это уровень сигнала в "процентах", а децибелы вычисляем вычитая 100,
3. Если значение отрицательное, то это уровень сигнала в децибелах, а "проценты" можно получить прибавив 100.

Что касается C/N или CNR, то что там за цифры на стандартном ядре и как из них вычислить децибелы, я сказать затрудняюсь. На модифицированном - цифры верные.

Думаю, лучше всего в случае активации отображения статистики в децибелах, выдавать предупреждение о том, что данные зависят от тюнера / драйвера и расчётные значения могут быть не верными.

У меня есть ещё пара тюнеров устаревшего стандарта DVB-S. Как будет время - гляну, что показывают они.

**Comment by vl-nix** [comment]
> С этими децибелами похоже не всё так просто!

> Думаю, лучше всего в случае активации отображения статистики в децибелах, выдавать предупреждение о том, что данные зависят от тюнера / драйвера и расчётные значения могут быть не верными.

Это ожидаемо, и в процессе разработки программы, является обычным делом.

> У меня есть ещё пара тюнеров устаревшего стандарта DVB-S. Как будет время - гляну, что показывают они.

Не стоит тратить чрезмерно времени, потому что не создать правила на каждое устройство.
Есть путь проще, дополнительное окно с возможностью создания правил ...

**Comment by vl-nix** [comment]
> выдавать предупреждение о том, что данные ... быть не верными

Уже присутствует

[decibel-pref-win.diff.tar.gz](https://github.com/vl-nix/dvbv5-gtk/files/5012020/decibel-pref-win.diff.tar.gz)

**Comment by vl-nix** [comment]
Обновлено
