### ISSUE TITLE
Зависание в режиме отладки DVB_DEBUG=1 dvbv5-gtk

### ISSUE THREAD

**Issue by Ro-Den** [vl-nix/dvbv5-gtk#8]
Привет!

При запуске в режиме отладки `DVB_DEBUG=1 dvbv5-gtk` программа зависает. Возможно из-за слишком частого обновления данных (информация в терминале отображается) или может быть у меня компьютер слишком слабый.

Я решил при помощи таймаута в `dvbv5.c` по аналогии с `beep` (espeak), который ты добавлял по моей просьбе:

`    

    time_t t_cur;
    time ( &t_cur );
    
    if ( ( t_cur - dvbv5->t_fe_start ) >= 4 )
    {
        DvbStat dvbstat = dvb_fe_stat_get ( bitrate, dvbv5->dvb );
        time ( &dvbv5->t_fe_start );
    
        if ( dvbstat.sgl || dvbstat.snr )
        {
            dvbv5_set_status ( dvbstat.freq, dvbv5 );

            level_set_sgn_snr ( (uint8_t)dvbstat.qual, ( dvbstat.sgl_str ) ? dvbstat.sgl_str : "Signal", 
                ( dvbstat.snr_str ) ? dvbstat.snr_str : "Snr", (double)dvbstat.sgl, (double)dvbstat.snr, dvbstat.fe_lock, dvbv5->level );
        }
        else
        {
            dvbv5_stats_clear ( dvbv5 );
        }

        free ( dvbstat.sgl_str );
        free ( dvbstat.snr_str );
    }

	return TRUE;
`

Плюс также часто бывают зависания на транспондерах со слабым сигналом, который не удаётся принять. Опять же, возможно проблема в моей ТВ-карте. Удалось побороть увеличением таймаута в `dvb.c`: `g_timeout_add ( 2500, (GSourceFunc)dvb_zap_check_fe_lock, dvb );`

**Comment by vl-nix** [comment]
Скорее всего, это останется без изменений

> Плюс также часто бывают зависания на транспондерах со слабым сигналом, который не удаётся принять.

Нет, это библиотека - libdvbv5 - нужно самостоятельно ( если необходимо ) вносить изменения в эту библиотеку
